"""change_intelligence

Revision ID: 2445db697559
Revises: a539a7bee9eb
Create Date: 2026-09-24 11:15:10.571554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2445db697559'
down_revision: Union[str, Sequence[str], None] = 'a539a7bee9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delta_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expected_delta_id', sa.Integer(), nullable=False),
    sa.Column('observed_delta_id', sa.Integer(), nullable=False),
    sa.Column('expected', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('unexpected', sa.JSON(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delta_report_expected_delta_id'), 'delta_report', ['expected_delta_id'], unique=False)
    op.create_index(op.f('ix_delta_report_observed_delta_id'), 'delta_report', ['observed_delta_id'], unique=False)
    op.create_table('expected_delta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_delta_requirement_id'), 'expected_delta', ['requirement_id'], unique=False)
    op.create_table('observed_delta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expected_delta_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('replay_run_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observed_delta_expected_delta_id'), 'observed_delta', ['expected_delta_id'], unique=False)
    op.create_index(op.f('ix_observed_delta_skill_id'), 'observed_delta', ['skill_id'], unique=False)
    # ### end Alembic commands ###
    # 注：autogenerate 对 raw_event 的 3 条假 NOT NULL alter_column（id/payload/created_at）已删除——
    # SQLite 下既有表结构与模型一致，属已知 autogenerate 噪音（第 4 次出现）


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observed_delta_skill_id'), table_name='observed_delta')
    op.drop_index(op.f('ix_observed_delta_expected_delta_id'), table_name='observed_delta')
    op.drop_table('observed_delta')
    op.drop_index(op.f('ix_expected_delta_requirement_id'), table_name='expected_delta')
    op.drop_table('expected_delta')
    op.drop_index(op.f('ix_delta_report_observed_delta_id'), table_name='delta_report')
    op.drop_index(op.f('ix_delta_report_expected_delta_id'), table_name='delta_report')
    op.drop_table('delta_report')
    # ### end Alembic commands ###
