"""normalized_event transaction_window

Revision ID: 2de33db18300
Revises: 24574ffda624
Create Date: 2026-09-23 17:44:27.882809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2de33db18300'
down_revision: Union[str, Sequence[str], None] = '24574ffda624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=500), nullable=False),
    sa.Column('page_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_event_session_id'), 'normalized_event', ['session_id'], unique=False)
    op.create_table('transaction_window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('window_seq', sa.Integer(), nullable=False),
    sa.Column('anchor_event_id', sa.Integer(), nullable=False),
    sa.Column('member_event_ids', sa.JSON(), nullable=False),
    sa.Column('idle_ms', sa.Integer(), nullable=False),
    sa.Column('max_window_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_window_session_id'), 'transaction_window', ['session_id'], unique=False)
    # 注：autogenerate 同时检出 raw_event 三列 NOT NULL 漂移（源于上一版手写表重建 SQL），
    # SQLite 不支持 ALTER COLUMN SET NOT NULL，且与本迁移目标无关，已剪除。
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_transaction_window_session_id'), table_name='transaction_window')
    op.drop_table('transaction_window')
    op.drop_index(op.f('ix_normalized_event_session_id'), table_name='normalized_event')
    op.drop_table('normalized_event')
