"""replay_run

Revision ID: a539a7bee9eb
Revises: b0bb1a80decf
Create Date: 2026-09-24 09:19:52.850696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a539a7bee9eb'
down_revision: Union[str, Sequence[str], None] = 'b0bb1a80decf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('executed', sa.JSON(), nullable=True),
    sa.Column('assertion_results', sa.JSON(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_run_skill_id'), 'replay_run', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replay_run_skill_id'), table_name='replay_run')
    op.drop_table('replay_run')
    # ### end Alembic commands ###
