"""semantic_action

Revision ID: cac56092f499
Revises: 470c6f225124
Create Date: 2026-09-23 16:41:21.918806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac56092f499'
down_revision: Union[str, Sequence[str], None] = '470c6f225124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('window_seq', sa.Integer(), nullable=False),
    sa.Column('anchor_seq', sa.Integer(), nullable=False),
    sa.Column('anchor_type', sa.String(length=20), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('api_calls', sa.JSON(), nullable=False),
    sa.Column('state_signals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_action_session_id'), 'semantic_action', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_action_session_id'), table_name='semantic_action')
    op.drop_table('semantic_action')
    # ### end Alembic commands ###
